server:
  port: 8080

spring:
  application:
    name: kafka-flow-monitor

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        msg_e2e_latency_seconds: true
        msg_lag_latency_seconds: true
        msg_internal_latency_seconds: true
        msg_size_bytes: true

monitor:
  message:
    big-threshold-bytes: 1048576
    big-trace-max: 200
  prometheus:
    base-url: http://localhost:9090
    task-metrics-enabled: true
    task-metrics-max-series: 5000
  kafka:
    main:
      enabled: false  
      # enabled: true
      group-id: monitor-main-group
      topic: monitor-topic
      processed-topic: monitor-topic-processed
    observer:
      group-id: monitor-observer-group
      topics: state,SUNYARD,AGENT,competence
  latency:
    timeout-seconds: 0.8
  demo:
    producer:
      # enabled: true
      enabled: false
      topic: monitor-topic
      rate-ms: 1000
