groups:
  - name: kafka_alerts
    rules:
      - alert: KafkaBrokerDown
        expr: kafka_controller_kafkacontroller_activecontrollercount == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Kafka Broker is down"
          description: "Kafka Broker has been down for more than 1 minute."
